export const WORKS_DATA_REQUEST = "WORKS_DATA_REQUEST";
export const WORKS_DATA_REQUEST_SUCCESS = "WORKS_DATA_REQUEST_SUCCESS";

export const APP_SETTINGS_REQUEST = "APP_SETTINGS_REQUEST";
export const APP_SETTINGS_REQUEST_SUCCESS = "APP_SETTINGS_REQUEST_SUCCESS";

export const SHOW_PAGE_PRELOADER = "SHOW_PAGE_PRELOADER";
export const HIDE_PAGE_PRELOADER = "HIDE_PAGE_PRELOADER";

export const SENDING_MAIL_START = "SENDING_MAIL_START";
export const SENDING_MAIL_SUCCESS = "SENDING_MAIL_SUCCESS";
export const SENDING_MAIL_FAILED = "SENDING_MAIL_FAILED";

export const HANDLE_ERROR = "HANDLE_ERROR";
