export const WORKS_REQUEST = "WORKS_REQUEST";
export const WORKS_REQUEST_SUCCESS = "WORKS_REQUEST_SUCCESS";

export const APP_SETTINGS_REQUEST = "APP_SETTINGS_REQUEST";
export const APP_SETTINGS_REQUEST_SUCCESS = "APP_SETTINGS_REQUEST_SUCCESS";

export const HIDE_PAGE_PRELOADER = "HIDE_PAGE_PRELOADER";

export const SHOW_CONTENT_PRELOADER = "SHOW_CONTENT_PRELOADER";
export const HIDE_CONTENT_PRELOADER = "HIDE_CONTENT_PRELOADER";

export const HANDLE_ERROR = "HANDLE_ERROR";
